### ISSUE TITLE
Bug: For some reason the bot tried to edit a message with the same content in the message

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#65]
**Describe the bug**
For some reason the bot tried to edit a message with the same content in the message, the function to check the difference of the message hash did not work.
Log link: https://obervinov312.grafana.net/goto/H7oNhEsIR?orgId=1
Link to archive log: https://drive.proton.me/urls/3930MZ5AHR#xtcLKuTWDJ55
Error message:
```bash
Exception in thread Thread-message-updater:
Traceback (most recent call last):
  File "/home/pyinstabot-downloader/app/src/bot.py", line 513, in status_message_updater_thread
    update_status_message(user_id=user_id)
  File "/home/pyinstabot-downloader/app/src/bot.py", line 286, in update_status_message
    editable_message = telegram.send_styled_message(
  File "/home/pyinstabot-downloader/app/.venv/lib/python3.9/site-packages/telegram/telegram.py", line 197, in send_styled_message
    response = self.telegram_bot.edit_message_text(
  File "/home/pyinstabot-downloader/app/.venv/lib/python3.9/site-packages/telebot/__init__.py", line 4618, in edit_message_text
    result = apihelper.edit_message_text(
  File "/home/pyinstabot-downloader/app/.venv/lib/python3.9/site-packages/telebot/apihelper.py", line 1356, in edit_message_text
    return _make_request(token, method_url, params=payload, method='post')
  File "/home/pyinstabot-downloader/app/.venv/lib/python3.9/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/pyinstabot-downloader/app/.venv/lib/python3.9/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
```

**Additional context**
Information about where the bug is happening:
There seems to be a conflict between the thread updating the message and a manual call of the method of updating the message in the thread that handles incoming messages.

**Possible correction**
If you have a possible solution to the bug, please describe it.
1. Find solutions to avoid two threads competing for the same method call.
2. Improve the hash collation method so that it does not allow attempting to edit a message with the same content that is already in it.
3. Add a message `status` column to block the update process if it is already in progress. That is, to protect against method competition

**Screenshots**
None

**Check list after fixing the bug**
- [x] There is no collision between the two streams anymore.
- [x] The message is no longer editable with the same hash.

**Comment by obervinov** [comment]
It is still playing...
Need to add:
- [ ] comparison of hashes of existing message and new one when batch adding message list to the queue
